### ISSUE TITLE
rmol.generate_conformers problem

### ISSUE THREAD

**Issue by Mengo-ye** [cole-group/FEgrow#74]
When I generate conformations using `rmol.generate_conformers(num_conf=5, minimum_conf_rms=0.5)`, it works correctly. However, when I used `rmol.generate_conformers(num_conf=200, minimum_conf_rms=0.5)` to generate conformations, I encountered an error that I couldn't resolve despite significant effort. I would appreciate your assistance and hope you can provide a solution. Thank you.
```
rmol.generate_conformers(num_conf=200,
  File "/home/mengo/SOFTWARE/anaconda3/envs/Fegrow/lib/python3.10/site-packages/fegrow/package.py", line 150, in generate_conformers
    cons = generate_conformers(self, num_conf, minimum_conf_rms, **kwargs)
  File "/home/mengo/SOFTWARE/anaconda3/envs/Fegrow/lib/python3.10/site-packages/fegrow/conformers.py", line 114, in generate_conformers
    temp_mol = ConstrainedEmbedR2(
  File "/home/mengo/SOFTWARE/anaconda3/envs/Fegrow/lib/python3.10/site-packages/fegrow/conformers.py", line 153, in ConstrainedEmbedR2
    raise ValueError("Could not embed molecule.", mol, coordinates_map)
ValueError: ('Could not embed molecule.', <rdkit.Chem.rdchem.Mol object at 0x15096ff58c80>, {0: <rdkit.Geometry.rdGeometry.Point3D object at 0x1509801488c0>, 1: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014b7c0>, 2: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014bac0>, 4: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014ba40>, 5: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014b940>, 9: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014b9c0>, 12: <rdkit.Geometry.rdGeometry.Point3D object at 0x15098014bc40>})
```

**Comment by bieniekmateusz** [comment]
Thanks for raising the issue. Would it be possible to share the files to reproduce this issue?

**Comment by Mengo-ye** [comment]
@bieniekmateusz Thank you for your quick response. Here is my file, with `attachment_index = 13`. Thank you.
[raise_issue.zip](https://github.com/user-attachments/files/16476999/raise_issue.zip)

**Comment by bieniekmateusz** [comment]
Thank you. I assume that the index `13` is on the `gorw` file. Is there a specific index I should use on the `resi` group?

**Comment by Mengo-ye** [comment]
@bieniekmateusz Thank you again for your quick response. I have renamed the files according to the tutorial you provided. File `scaffold.sdf` is the ligand scaffold with `attachment_index = 13`, and File `gorwing_frag.mol` is the growing fragment. I followed the tutorial's instructions and replaced the growing H atom with R. I appreciate your help once again. Best wishes!
[raise_issue_v2.zip](https://github.com/user-attachments/files/16481134/raise_issue_v2.zip)

**Comment by bieniekmateusz** [comment]
Oh I see. I'll use that then to reproduce the issue. I take it you mean a specific jupyter notebook file. Which notebook is it? Thanks.

**Comment by Mengo-ye** [comment]
@bieniekmateusz Thank you for your reply. I referenced the two notebooks: `notebooks/1_basic_tutorial_full.ipynb` and `notebooks/2_tutorial_single_mol.ipynb.` I look forward to your response. Best wishes!

**Comment by bieniekmateusz** [comment]
Found it. We added some flexibility with allowing R-atoms in the scaffold. This was not accounted for in the constraining algorithm, which tried to match the * atom to a random hydrogen, breaking down the RDKit's embedding that we rely on internally. I'll merge the fix shortly.

**Comment by bieniekmateusz** [comment]
I've merged the fix. Would you be able to confirm that the current github version resolves this issue for you? Thanks

**Comment by Mengo-ye** [comment]
@bieniekmateusz Thank you for your work. I’ll give it a try. Thanks again, and best wishes!

**Comment by Mengo-ye** [comment]
@bieniekmateusz Hi, I tried the latest github version but still encountered the same issue. Looking forward to your response. Thanks again, and best wishes!
```
fegrow/lib/python3.11/site-packages/fegrow/conformers.py", line 166, in ConstrainedEmbedR2
    raise ValueError("Could not embed molecule.", mol, coordinates_map)
ValueError: ('Could not embed molecule.', <rdkit.Chem.rdchem.Mol object at 0x7fb8c8652730>, {0: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c86979c0>, 1: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697a40>, 2: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697ac0>, 4: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697b40>, 5: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697bc0>, 9: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697c40>, 12: <rdkit.Geometry.rdGeometry.Point3D object at 0x7fb8c8697cc0>})
```

**Comment by bieniekmateusz** [comment]
Hi. I have only now realised that there was already an R-atom in the scaffold. And it was in fact that that was responsible for the issue I was seeing (which had the same "could not embed molecule" error). 

Is this what you are trying to do?
```
from rdkit import Chem
import fegrow

init_mol = Chem.SDMolSupplier('gorw_frag.mol', removeHs=False)[0]
scaffold = fegrow.RMol(init_mol)

r = Chem.MolFromPDBFile('resi_allh.pdb', removeHs=False)
r.GetAtomWithIdx(13).SetAtomicNum(0)

merged = fegrow.build_molecule(scaffold, r)

t = merged.generate_conformers(num_conf=200, minimum_conf_rms=0.5)

```

**Comment by bieniekmateusz** [comment]
Heya, have you had any more luck with this script? If it's all working fine, please close the issue. Thanks

**Comment by Mengo-ye** [comment]
@bieniekmateusz Ok, everything is clear now. Thanks for your help, and I wish you a happy and fulfilling life!
